### ISSUE TITLE
Windows 10: 'mix' is not executable

### ISSUE THREAD

**Issue by davaeron** [pantajoe/vscode-elixir-credo#10]
Version: 1.54.2 (user setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

I have 'C:\Program Files (x86)\Elixir\bin\' in path, 'mix' is in that path and i can run 'mix credo' in terminal, but when i try to use Elixir Linter (Credo) extension it prints this error message:
```
`C:\Program Files (x86)\Elixir\bin\mix` is not executable.
        Try setting the option in this extension's configuration "elixir.credo.executePath"
        to the path of the mix binary.
```
Changing  "elixir.credo.executePath" does not help.

**Comment by pantajoe** [comment]
Hi @davaeron !
I see. The `mix` command which resides in a binary file in the path `C:\Program Files (x86)\Elixir\bin` is actually `mix.exe` right?
If the file is named `.exe`, I believe the extension cannot find it. If so, I guess that this issue occurs only on Windows, and I can easily fix this to search for a `mix.exe` file in the specified `executePath`.

**Comment by davaeron** [comment]
![Screenshot 2021-03-15 163002](https://user-images.githubusercontent.com/33601/111161236-f9b19a00-85ab-11eb-9541-538ea346723d.png)

There are `mix`, `mix.bat` and `mix.ps1`. AFAICS no `mix.exe`.
Change `executePath` to `mix.bat` please.

**Comment by pantajoe** [comment]
Ah, I see. I am no expert when it comes to Windows executables, so I'll change it to search for `mix.bat` then.

**Comment by pantajoe** [comment]
Hey @davaeron, I released a new version (hopefully) supporting Windows. I have no Windows device, I'd appreciate it very much if you could test it and get back to me!

**Comment by davaeron** [comment]
It works now! Thank you!
