### ISSUE TITLE
".credo.exs file does not exist. Ignoring..." (Windows 10)

### ISSUE THREAD

**Issue by Ovyerus** [pantajoe/vscode-elixir-credo#18]
#### VSCode Info
Version: 1.56.0-insider (user setup)
Commit: 845efe5d8e31079cc858131c95c36103d9439e74
Date: 2021-04-09T09:50:06.816Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

---

Trying to use this plugin but I'm getting a constant `.credo.exs file does not exist. Ignoring...` in any Elixir file in my project - even the `.credo.exs`. Even setting `elixir.credo.configurationFile` in my settings doesn't change anything.

![image](https://fire.is-fi.re/5kiewCh.png)

**Comment by pantajoe** [comment]
Hey! Hm, that's odd... I do not code on Windows, so I have no idea what might be causing this issue, I'll try to replicate it tomorrow. Do you get any linter messages though, when having 2 consecutive blank lines for instance?

**Comment by Ovyerus** [comment]
Yeah not getting any linter messages either. Seems to just be completely disabled.

**Comment by pantajoe** [comment]
So... turns out, the solution was pretty simple. I used implementations that did not respect the platform-specific path separator, which is `\` on Windows. 😅  Should be all good now. I released the fix, so you should be able to use the extension. Let me know if it works!

**Comment by Ovyerus** [comment]
Yup looks like its working now. Thanks a lot 😁
