### ISSUE TITLE
After saving in vscode with this extension enabled, `recompile` in IEx session does not work

### ISSUE THREAD

**Issue by doughsay** [pantajoe/vscode-elixir-credo#282]
After saving in vscode with this extension enabled, `recompile` in IEx session does not work, and the new code will not be loaded.  This forces you to quit IEx completely and start a new session.

**Comment by pantajoe** [comment]
Hi! Could you maybe disclose the exact reproduction steps, and what exactly happened, and what you would have expected to happen?

**Comment by doughsay** [comment]
Sorry, I can't reproduce this anymore.  Either it's fixed, or there's some more nuance to when it happens.  If I learn anything more I'll come back and add more details; for now I'll close.
