### ISSUE TITLE
".credo.exs file does not exist. Ignoring..." (warning)

### ISSUE THREAD

**Issue by makarichevss** [pantajoe/vscode-elixir-credo#289]
Hi!

I still get ".credo.exs file does not exist. Ignoring..." warning after installing Credo in VS Code on Windows 11 Pro.
The problem is that there is some Credo inspection that requires **.credo.exs** in the root of the mix project.
Right after I create such file (empty inside), the warning is gone.

Could you please turn off this inspection, so there is no need to create that unnecessary **.credo.exs** file?

**Comment by pantajoe** [comment]
Hi, I'm aware that this is annoying if you don't use a custom linting config. But, I believe that most users would use a custom configuration instead of credo's default one.

You can go into the extension settings and ignore this warning. Or you can specify it in your settings JSON: `"elixir.credo.ignoreWarningMessages": true`

see this issue: https://github.com/pantajoe/vscode-elixir-credo/issues/4#issuecomment-834445986

**Comment by richardjharris** [comment]
I also encountered this. It would be good if the error was updated to suggest creating a file, e.g. via `mix credo gen.config`. That would save users googling and finding this page.

**Comment by makarichevss** [comment]
Yes, from my point of view the best solution would be not to mask this bug or ask users to solve it manually, but offer some automatic fix.
Please add an option for credo to ask whether to automatically add "elixir.credo.ignoreWarningMessages": true into settings.json.

**Comment by pantajoe** [comment]
@makarichevss  I agree. The best solution would be to show a notification that you use the default credo config if no config file is present. Then you can either click on "Generate Config" (that runs `mix credo gen.config` or "Ignore" which only ignores this type of warning message (not the rest).

The present config to ignore all warning messages was more of a dirty temporary fix 😄

**Comment by brunoparga** [comment]
I was getting ".credo.exs does not exist" even though it is right there in the root of the umbrella app. Then I realized it should be within each of the apps in the umbrella, so I symlinked to it. Maybe there could be a hint to do that?

**Comment by pantajoe** [comment]
> I was getting ".credo.exs does not exist" even though it is right there in the root of the umbrella app. Then I realized it should be within each of the apps in the umbrella, so I symlinked to it. Maybe there could be a hint to do that?

That's actually a good suggestion, @brunoparga ! 👍🏽 Would you mind picking this up and adding this to the README?

**Comment by brunoparga** [comment]
Sure!

**Comment by pantajoe** [comment]
Closed via #471
