### ISSUE TITLE
Tag filter options

### ISSUE THREAD

**Issue by skwerlman** [pantajoe/vscode-elixir-credo#30]
I have a credo check that compares the module name to the file name to ensure they match. This check always fails when run from vscode, since the file name credo sees is 'stdin'. Currently, to work around this, I have to duplicate my whole credo config except for this one check, and tell vscode-elixir-credo to use the duplicated config

It would be preferable to simply set `tags: [:__initial__, :no_editor]` on the faulty check and tell vscode-elixir-credo to pass `--checks-without-tag no_editor` to credo

I can image a scenario exists where the inverse option, `--checks-with-tag some_tag`, is useful as well

**Comment by pantajoe** [comment]
Seems really frustrating. I'll work on this and notify as soon as I released a version with this feature!

**Comment by pantajoe** [comment]
@skwerlman Hey, it's been a while, but I've published a new version of this extension (`v0.6.0`) and I added the configuration options to ignore checks with certain tags (or exclude every check but those with specified tags). 🚀 

Check it out and please let me know if it solves your problem.

**Comment by skwerlman** [comment]
yep, this works perfectly! thanks!
