### ISSUE TITLE
Can't work with credo v1.6.7

### ISSUE THREAD

**Issue by leandroluk** [pantajoe/vscode-elixir-credo#349]
## Details 

I trying to use the extension with latest version of credo but when I put the configuration described in creed's README and save an example file, VSCode gives an error and a warn:

![image](https://user-images.githubusercontent.com/8602982/220376004-e93b829c-f4cf-4474-b7b6-9bbd00bec5e3.png)

![image](https://user-images.githubusercontent.com/8602982/220376049-0525bb75-253f-4ca1-a78e-d265a7f90900.png)

## Steps to reproduce

1. add extension to VSCode
2. create new project using command `mix new example` and access it with vscode
3. add the credo to project as defined in [docs](https://hexdocs.pm/credo/installation.html)
   ```elixir
    defp deps do
      [
        {:credo, "~> 1.6", only: [:dev, :test], runtime: false}
      ]
    end
   ```
4. open the first file of project in `lib/example.ex` and press `command + s` some times

## System Info

- **SO**: MacOS Venntura v13.2.1
- **VSCode**: v1.75.1
- **Credo (Elixir Linter)**: v0.8.2

## Other info's

When install credo v1.5.x the extension works correctly

**Comment by znorris** [comment]
@leandroluk I'm currently using credo 1.6.7, macOS 13.3.1, and credo (elixir linter) for VSCode v0.8.2. I do receive errors like mentioned in #344.

I would recommend you check the output of the extension and see if credo was able to restart and successfully execute.

Try adding some line to the example project that will elicit a credo response.
For instance this code:

```elixir
K8s.Client.apply()
```

It should be underlined and credo will report:

> Nested modules could be aliased at the top of the invoking module. (design:Credo.Check.Design.AliasUsage)

If you still have issue, please include the VSCode extension logs. I'm not a contributor but happy to help.

**Comment by pantajoe** [comment]
Hi, thanks for your reply @znorris. Despite similar error and warning messages, the extension works properly and you receive linting warnings in your editor?
