### ISSUE TITLE
Extension errors when CMD/CTRL+hovering symbols from other files

### ISSUE THREAD

**Issue by jaminthorns** [pantajoe/vscode-elixir-credo#42]
When holding CMD/CTRL and hovering a module or function from another file, it seems like Credo tries to run on that file but fails, causing this error message to be displayed as a notification:

> Command `/Users/jamin/.asdf/shims/mix credo` returns empty output! Please check your configuration. Did you add or modify your dependencies? You might need to run `mix deps.get` or recompile.

The error only occurs when the file of the hovered symbols is _not_ open:

https://user-images.githubusercontent.com/6618434/144095983-4dc7308a-22a0-4306-9b1a-e7c4c6c66591.mov

The error does _not_ occur when the file is already open:

https://user-images.githubusercontent.com/6618434/144096028-6234a2ed-0111-4030-b1b2-d9d48a5ebab9.mov

This is the debug log (`elixir.credo.enableDebug` set to `true`) when duplicating the error:

```
> Retreiving credo information: Executing credo command `/Users/jamin/.asdf/shims/mix credo info --format json --verbose` for /Users/jamin/Projects/vscode_elixir_issue/lib/other_module.ex in directory /Users/jamin/Projects/vscode_elixir_issue

> Removing linter messages and cancel running linting processes for /Users/jamin/Projects/vscode_elixir_issue/lib/other_module.ex.

> Command `/Users/jamin/.asdf/shims/mix credo` returns empty output! Please check your configuration. Did you add or modify your dependencies? You might need to run `mix deps.get` or recompile.
```

The extension still functions correctly (linting open Elixir files), though.

## Steps to Reproduce

1. Create a new Elixir project with `mix new`.
2. Install Credo and set up config with `mix credo.gen.config`.
3. Create a new file and module (`OtherModule`) with a function (`some_function`).
4. Reference that function in another file and module (`MainModule`).
5. Close all files except the one containing `MainModule`.
6. Hold CMD/CTRL and hover over `OtherModule` or `some_function`.
7. Observe the "returns empty output" error in a notification.

**Comment by pantajoe** [comment]
Hello there! Thanks for bringing that up. That seems to happen because of https://github.com/microsoft/vscode/issues/109908: When the hover popup is opened it triggers the event that a document has open, and, thus, the document starts a linting process. However, immediately afterwards, vscode triggers the event that the document has been closed. This in turn triggers all running credo processes for this document to be cancelled.

I'll release a fix where SIGTERM errors on credo processes will not be reported.
