### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by pdavies** [pantajoe/vscode-elixir-credo#466]
Hi, it's over a year since the last commit to this repo, and issues and PRs have lately gone without a response.

@pantajoe this isn't a complaint - in fact, thanks for contributing this extension! - but do you plan to resume maintaining the extension or to deprecate it?

I've been hit by some of the open issues around looking for `.credo.exs` in the wrong places, and I'm potentially interested in contributing a fix beyond the existing blunt option to suppress warnings, but looking at this repo I'm not sure if contributions would ever be merged. Alternatively, I'm _potentially_ interested in taking over maintenance if you're too busy (but as far as I can tell, there's no clean way to transfer ownership of a published vscode extension, so some headscratching required there...)

**Comment by pantajoe** [comment]
Hi @pdavies, appreciate you asking!

The truth is I don't actively code in Elixir anymore, but I'd love to continue (or rather start again) maintaining this VS Code extension.

Alongside work and personal stuff, I didn't have enough time to prioritize this project in the last year, but I'm glad to announce that I've finally managed to create a v1.0 version with a complete rewrite, so the codebase will hopefully be easier to understand and less scary for others like you contribute!

If you're interested in contributing, I'd strongly encourage you to try and solve any present issues that you found yourself or tackle any issue that's marked with one of the labels "good first issue", "feature", or "bug".

If you have any questions, feel free to create a PR against this repo and tag me there 👍🏽.
