### ISSUE TITLE
Configuration file setting doesn't work

### ISSUE THREAD

**Issue by alex-strizhakov** [pantajoe/vscode-elixir-credo#6]
Hi! 👋

Big thanks for your work on the extension. 

There is one problem with extension configuration through `credo` configuration file.

I've set `configurationFile` option into `settings.json` file, like this: 
```json
"elixir.credo.configurationFile": "config/.credo.exs"
```

and have these settings in `.credo.exs`.
```elixir
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["mix.exs", "lib/"],
        excluded: ["test/"]
      }
    }
  ]
}
```
When I run `mix credo` it works as expected, but in vscode, I have warnings in test modules, that `Modules should have a @moduledoc tag.`
<img width="707" alt="Screenshot 2021-01-31 at 13 29 43" src="https://user-images.githubusercontent.com/1472667/106381231-63912e00-63c8-11eb-8625-c79bd4ce80f7.png">

Am I doing something wrong?

**Comment by pantajoe** [comment]
Hi! Thanks for pointing that out. No, you are not doing anything wrong 😄 Simply put, this is not supported yet. The extension does not respect such preferences. However, I'll work on that soon. Currently, my time is rather limited, but I'll let you know here as soon as I got something ready.

**Comment by pantajoe** [comment]
Hey @alex-strizhakov, I released a new version respecting credos' configuration regarding file inclusion/exclusion.
Thus, I'll close this issue.
