### ISSUE TITLE
Feature request: Publish extension to open-vsx.org (VSCodium marketplace)

### ISSUE THREAD

**Issue by brunoparga** [pantajoe/vscode-elixir-credo#7]
Currently, this extension cannot be installed from VSCodium interface, and it would be great to do so.
As far as I have read in VSCodium documentation (https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) there is a wiki documenting the process https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Hope you could consider doing it.

**Comment by pantajoe** [comment]
Sure, I completely neglected it, but it could be a nice addition. I'll work on this in the next week, and I'll notify you here as soon as it's done.

**Comment by pantajoe** [comment]
@brunoparga Hey, I managed to publish the current version to the Open VSX Registry: https://open-vsx.org/extension/pantajoe/vscode-elixir-credo!
