### ISSUE TITLE
Add support for multiple default .credo.exs locations

### ISSUE THREAD

**Issue by nsweeting** [pantajoe/vscode-elixir-credo#81]
The credo docs specify that the `.credo.exs` config file can live in either the root project folder or the `config` folder (https://hexdocs.pm/credo/config_file.html). Either of these locations should be valid default options.

**Comment by pantajoe** [comment]
Thanks! I'll update you as soon as it's ready.

**Comment by pantajoe** [comment]
Fixed in newest release 0.7.3
